### ISSUE TITLE
Có cần BigNum?

### ISSUE THREAD

**Issue by baosws** [baosws/BigNum#1]
BigInt và BigFloat chỉ có phần chung là set_bit và get_bit, các thao tác khác có chung tên nhưng xử lý khác nhau, như vậy thì có cần tới lớp BigNum không?

**Comment by chienpm304** [comment]
Tui nghĩ là nên có cho nó tổng quát, rất có thể các hàm khác xử lí khác nhưng có phần gì đó chung thì nên viết ở BigNum !
